### ISSUE TITLE
\GetTitleStringNonExpand and \GTS@PredefinedLeftCmds

### ISSUE THREAD

**Issue by mrpiggi** [ho-tex/gettitlestring#2]
The different behavior of removing predefined commands only at the beginning of a string should at least be documented. 
```latex
\listfiles
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{gettitlestring}
\begin{document}
\GetTitleString{foo\index{foo}}
\meaning\GetTitleStringResult

\GetTitleString{\index{foo}foo}
\meaning\GetTitleStringResult
\end{document}
```

**Comment by u-fischer** [comment]
It is documented in `\GetTitleStringNonExpand`:

> It is especially removed at the start
> of the textiand spaces are removed from the end. Currently only \label
> is removed in the whole string, if it is not hidden inside curly braces or
> part of macro definitions.

**Comment by mrpiggi** [comment]
Oh, sorry for the noise. I was just testing the interaction between `nameref` and `gettitlestring` and read the documentation obviously very inattentive. My bad.
