### ISSUE TITLE
Feature Request: \GetTitleStringProtectedExpand

### ISSUE THREAD

**Issue by mrpiggi** [ho-tex/gettitlestring#3]
Something like protected expansion would be nice as this could be used by `nameref` for section headings.
```tex
\newcommand{\GetTitleStringProtectedExpand}[1]{%
  \def\GetTitleStringResult{#1}%
  \begingroup
    \GTS@DisablePredefinedCmds
    \GTS@DisableHook
    \protected@edef\x{\endgroup
      \noexpand\def\noexpand\GetTitleStringResult{%
        \GetTitleStringResult
      }%
    }%
  \x
}
```

**Comment by u-fischer** [comment]
Do you have an example where this would make a difference?

**Comment by mrpiggi** [comment]
And again, sorry for the noise. I just was wondering, if something like `\section{something\,stupid}` would harm. But after a closer look I just saw, that `\let\protect\@unexpandable@protect` is done by `\GTS@DisablePredefinedCmds`. So `\edef` inside of `\GetTitleStringExpand` is actually `\protected@edef`.
